### PR TITLE
Branch object print

### PR DESCRIPTION
**Pull request by yiiyama**
This PR basically reverts the master to where it was on Friday. The error Brandon was seeing with the Friday version disappeared after clean & recompile. It seems that make in scram b failed to catch some header updates and left libPandaTreeObjects (or libPandaTreeFramework) in an inconsistent state.

### CODE REVIEW

**Comment by sidnarayanan** [comment]
Checking this on our analysis code now... recompiling after scram b clean takes a while!

**Comment by sidnarayanan** [comment]
Yeah, that did the trick. My code runs now. Sorry for the false alarm earlier about the crash.

**Comment by yiiyama** [comment]
Merged updates in #14 to this branch. We can merge this and close #14 once everyone is happy (I am).

**Comment by sidnarayanan** [comment]
I'm happy with it too. Maybe I'll wait for @blallen to show up and confirm, and then we can merge (and close #14)

**Comment by blallen** [comment]
Looks like this has everything now, so you can go ahead and merge it

**Pull request merged**
