### PR TITLE
RelVal

### PR DESCRIPTION
**Pull request by dabercro**
Added an executable ``testpanda`` that plots branches defined in ``RelVal/interface/EnumerateBranches.h``. Anyone who runs ``testpanda`` will get plots to show up in t3serv001.mit.edu/~${USER}/relval/

Example: http://t3serv001.mit.edu/~dabercro/relval/?d=171117_155230 which was output by running from ``/home/dabercro/cms/cmssw/CMSSW_8_0_29/src``
```
testprod PandaProd/Producer/cfg/data.root
```

The only other thing this package really needs it to automatically generate ``EnumerateBranches.h`` with ``generate.py``. I can spend time doing that but I might not be the fastest, so I thought a PR was worth it. People might also want to give input on additional ``.def`` formats to generate custom plots (like di-lepton mass peaks).

This PR also includes the updates for secondary vertexes and deep tagging in branch-008.

### CODE REVIEW

**Comment by dabercro** [comment]
I guess I should add, this is for #83

**Comment by dabercro** [comment]
Many of the branches are now automatically plotting successfully: http://t3serv001.mit.edu/~dabercro/relval/?d=171118_092150 There seem to be minor things to work out, such as number of entries on the histogram should be properly tracked, things like Jet.loose isn't filling properly (http://t3serv001.mit.edu/~dabercro/relval/171118_092150/chsAK4Jets/loose.pdf), and tinkering with bin width.

Good news is speed doesn't scale anywhere near proportionally to the number of plots.

**Comment by dabercro** [comment]
I'll guess I'll enumerate what's needed (sorry, it seems I'm mostly talking to myself):

- ~Event globals (such as npv) aren't plotted yet~
- ~Don't fill histogram for entries out of range (usually default values that are thrown out)~
- ~Check bools like Jet.loose that don't seem to match raw file contents~
- ~Play with bin width algorithm to avoid ugly plots like http://t3serv001.mit.edu/~dabercro/relval/171118_092150/ak4GenJets/numC.pdf~
- ~Don't plot things with zero entries (like chsCA15Jets)~
- ~Hide names of plots that are generated from terminal output~
- ~Sizes of collections~

I'll just edit this comment while I commit

Plots with common: http://t3serv001.mit.edu/~dabercro/relval/?d=171118_110324
Plots with nice looking axes for ints and bools: http://t3serv001.mit.edu/~dabercro/relval/?d=171118_131124
Final: http://t3serv001.mit.edu/~dabercro/relval/?d=171118_174704

**Comment by dabercro** [comment]
Okay, I think I'm finished now. Sorry for opening the PR prematurely. I didn't think I would work on this over the weekend, and I had invited Benedikt to contribute. Anyway, here are examples of the final product:

- MC: http://t3serv001.mit.edu/~dabercro/relval/?d=171118_174200
- Data: http://t3serv001.mit.edu/~dabercro/relval/?d=171118_174704

Note that they have different PandaTree commits because I didn't actually commit until after the MC page was generated. But I'm happy with all the plots now. Everything is automatically generated from generate.py and compiled by scram. This should be simple for the user to use.

**Review by yiiyama — APPROVED** [review]
This is really impressive.

**Comment by dabercro** [comment]
@yiiyama Thanks! I couldn't have done it without the nice classes in generate.py.

**Comment by dabercro** [comment]
Sorry, I caught one thing to fix. My binning strategy was not catching when there were three distinct values, so pfCandidates/q looked bad. The last commit fixed that.

- Old: http://t3serv001.mit.edu/~dabercro/relval/171118_174704/pfCandidates/q.pdf
- New: http://t3serv001.mit.edu/~dabercro/relval/171118_194933/pfCandidates/q.pdf

**Comment by dabercro** [comment]
@yiiyama @sidnarayanan @maierbenedikt Note, I do not have write access, and if no one merges this PR, I will probably tinker with minor things forever.

**Comment by yiiyama** [comment]
I can't find the button to allow you write access.. @maierbenedikt @sidnarayanan please help.

**Comment by yiiyama** [comment]
And @dabercro go do some physics! :)

**Comment by DylanHsu** [comment]
isn't it Settings -> Collaborators ?
By the way Yutaro you should sign up for the new slack: https://smhbb.slack.com

**Pull request merged**
