### PR TITLE
PandaTree updates for 009

### PR DESCRIPTION
**Pull request by DylanHsu**
still working, needs more features and testing before merge

### CODE REVIEW

**Comment by DylanHsu** [comment]
Maybe we don't need to save electron mvaCategory? It's only 1 byte/electron but it's technically redundant since you can get the mva category based on absolute eta: {0,0.8,1.479,2.5} for category 1,2,3

**Comment by yiiyama** [comment]
We don't have thousands of electrons per event, so storage footprint doesn't have to be considered.

**Comment by sidnarayanan** [comment]
It's my (small) preference that we skip electron mvaCategory, not so much for footprint, but for clutter reasons. We don't save photon isBarrel, jet isCentral, etc for the same reason, even though a lot of ID cuts are categorized in the same way.

**Comment by dabercro** [comment]
Why isn't the .def file changed in this PR?

**Comment by yiiyama** [comment]
ah did you edit all the files by hand? Shit that sucks.

**Comment by DylanHsu** [comment]
I have no idea what you're talking about

**Comment by dabercro** [comment]
Use this file to add variables: https://github.com/PandaPhysics/PandaTree/blob/master/defs/panda.def Then run `PandaTree/bin/generate.py` to create source files. It'll save us a lot of time and headaches. I'm sure Yutaro can explain the syntax to you if you have questions.

**Comment by DylanHsu** [comment]
Please merge this branch into master and make a new tag for 009, after which I will perform a unit test and  work with CP to submit the jobs.

**Comment by yiiyama** [comment]
Sorry! Wasn't aware it was not merged yet. Were you waiting for me?

**Pull request merged**
